export const SIGNUP_INIT = 'SIGNUP_INIT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNIN_INIT = 'SIGNIN_INIT';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const CHECK_CURRENT_USER = 'CHECK_CURRENT_USER';
export const CHECK_CURRENT_USER_SUCCESS = 'CHECK_CURRENT_USER_SUCCESS';
export const CHECK_CURRENT_USER_FAILURE = 'CHECK_CURRENT_USER_FAILURE';

export const SIGNOUT_INIT = 'SIGNOUT_INIT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE';
