export const CREATE_POST_INIT = "CREATE_POST_INIT";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";
// delete
export const DELETE_POST_INIT = "DELETE_POST_INIT";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const ADD_TITLE = "ADD_TITLE";
export const ADD_CONTENT = "ADD_CONTENT";

// get entries

export const INIT_GET_POSTS = "INIT_GET_POSTS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";
